language: node_js
script:
- npm build
deploy:
- provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_cd0e36adf9a3_key -iv $encrypted_cd0e36adf9a3_iv
  -in id_rsa_chrisjmccall.enc -out ~\/.ssh/id_rsa_chrisjmccall -d
