language: node_js
node_js:
- 8.9.4
script:
- npm run-script build
addons:
  ssh_known_hosts: chrisjmccall.com
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_cd0e36adf9a3_key -iv $encrypted_cd0e36adf9a3_iv
  -in .travis/id_rsa_chrisjmccall.enc -out .travis/id_rsa_chrisjmccall -d
